function [ vintdates ] = GetVintdates(api, series, frequency)

  %% Construct a query string and to pull the release dates
  url = sprintf([...
    'http://api.stlouisfed.org/fred/series/vintagedates?'...
    'series_id=%s' ...
    '&api_key=%s' ...
    '&file_type=json'],...
    series,...
    api);

  vintdates = loadjson(urlread(url));
  vintdates = cellfun(@(dt) datenum(dt, 'yyyy-mm-dd'), vintdates.vintage_dates)';

end
