function [returned] = releaseDates_(series)


  %% Get the release ID for the given series

    opt = fred.GlobalOptions();
    releaseURL = sprintf([...
            'https://api.stlouisfed.org/fred/series/release?' ...
            'series_id=%s' ...
            '&api_key=%s' ...
            '&realtime_start=1776-07-04',...
            '&realtime_end=9999-12-31',...
            '&file_type=json'],...
            series, ...
            opt.api);

    % Download
    fromFred = fred.ReadFredURL_(releaseURL, 1, opt.max_attempt);

    release_id = unique(cellfun(@(d) d.id, fromFred.releases));;

    % Make sure there's only one release ID for that series (seems like
    % there should be, but we check for that just in case)
    if length(release_id) > 1
      error(sprintf('Multiple release IDs for series %s', series))
    end


  %% Download the release dates for that release ID

    datesURL = sprintf([...
            'https://api.stlouisfed.org/fred/release/dates?' ...
            'release_id=%d' ...
            '&api_key=%s' ...
            '&include_release_dates_with_no_data=true' ...
            '&file_type=json'],...
            release_id, ...
            opt.api);
    fromFred = fred.ReadFredURL_(datesURL, 1, opt.max_attempt);
    fromFred = [fromFred.release_dates{:}];

    returned.series     = series;
    returned.release_id = release_id;
    returned.date       = fred.dtnum({fromFred.date}, 1)';


end
